# code: language=ansible
---
# tasks file for roles/snap

- name: Install snapd package
  ansible.builtin.package:
    name: snapd
    state: present
  become: true

- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ item }}"
    classic: true
  loop: "{{ snaps }}"

- name: Add .hidden file to hide snap folder
  ansible.builtin.file:
    src: "{{ role_path }}/files/hidden"
    dest: "{{ ansible_env.HOME }}/.hidden"
    state: link
    force: true
