# code: language=ansible
---
# tasks file for roles/postgresql

- name: Check required parameters
  ansible.builtin.assert:
    that:
      - postgresql_user is defined
      - postgresql_user_password is defined

- name: Install Postgresql
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop: "{{ packages }}"

- name: Enable postgresql
  become: true
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started
    daemon_reload: true

- name: Create user and role '{{ postgresql_db_user }}'
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    state: present
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_user_password }}"
    role_attr_flags: NOSUPERUSER,CREATEDB
