---
# tasks file for roles/postgresql

- name: Check required parameters
  assert:
    that:
      - postgresql_user is defined
      - postgresql_user_password is defined

- name: Install Postgresql
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ packages }}"

- name: Enable postgresql
  become: yes
  systemd:
    name: postgresql
    enabled: yes
    state: started
    daemon_reload: yes

- name: Create user and role '{{ postgresql_db_user }}'
  become: yes
  become_user: postgres
  postgresql_user:
    state: present
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_user_password }}"
    role_attr_flags: NOSUPERUSER,CREATEDB
