# code: language=ansible
---
# defaults file for roles/git

# Git
# Name used in commit messages
git_name: Michell Stuttgart

# Github username
github_username: mstuttgart

# If you use github, this should be the same as the email
#  used on Github
git_email: michellstut@gmail.com

# .gitconfig path
git_config_path: '{{ ansible_env.HOME }}'
