# code: language=ansible
---
# tasks file for roles/guake

- name: Install guake package
  become: true
  ansible.builtin.package:
    name: guake
    state: present

# Copy aliases
- name: Create symbolic link to guake aliases in '{{ bashrc_folder }}'
  ansible.builtin.file:
    src: '{{ role_path }}/files/aliases.bash'
    dest: '{{ bashrc_folder }}/guake.bash'
    state: link

# Restaure settings

- name: Restaure Guake Settings
  ansible.builtin.command: guake --restore-preferences '{{ role_path }}/files/settings'
  changed_when: true

# Add to autostart apps group

- name: 'Ensure directory exists: {{ autostart_path }}'
  ansible.builtin.file:
    path: '{{ autostart_path }}'
    state: directory
    mode: "0755"

- name: 'Copy guake .desktop file to {{ autostart_path }}'
  ansible.builtin.file:
    src: '{{ role_path }}/files/guake.desktop'
    dest: '{{ autostart_path }}/guake.desktop'
    force: true
    state: link
