# code: language=ansible
---
# tasks file for roles/nvm

- name: Install development requirements packages
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell: |
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ nvm_config_dir }}/nvm.sh"
    executable: /bin/bash

- name: Install node and set version
  ansible.builtin.shell: ". {{ nvm_config_dir }}/nvm.sh && nvm install --lts"
  args:
    creates: "{{ nvm_config_dir }}/versions/node"
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash

- name: "Create symbolic link to nvm aliases in {{ bashrc_folder }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/aliases.bash"
    dest: "{{ bashrc_folder }}/nvm.bash"
    state: link
    force: true
