---
# tasks file for roles/apt

- name: Upgrade apt
  become: yes
  apt: upgrade=yes
  when: package_upgrade

- name: Install apt packages
  become: yes
  apt:
    name: '{{ item }}'
  loop: '{{ packages }}'
  
- name: Install deb packages
  become: yes
  apt:
    deb: '{{ item.value }}'
  loop: '{{ deb_packages  | dict2items }}'
