---
# tasks file for python

- name: Install Python development packages
  package:
    name:
      - python3-dev
      - python3-pip
      - python3-venv
    state: present
  become: yes

- name: Create symbolic link to Python aliases/functions in '{{ ansible_env.HOME }}'
  file:
    src: '{{ role_path }}/files/aliases.bash'
    dest: '{{ bashrc_folder }}/python.bash'
    state: link
    force: yes