# code: language=ansible
---
# defaults vars for code
code_setting_path: '{{ ansible_env.HOME }}/.config/Code/User'

# plugins list
code_plugins:

  - albert.TabOut
  - alefragnani.Bookmarks
  - arcticicestudio.nord-visual-studio-code
  - dionmunk.vscode-notes
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - felipecaputo.git-project-manager
  - formulahendry.auto-close-tag
  - ginfuru.ginfuru-better-solarized-dark-theme
  - jdinhlife.gruvbox
  - jpotterm.simple-vim
  - kamikillerto.vscode-colorize
  - mechatroner.rainbow-csv
  - mrorz.language-gettext
  - ms-azuretools.vscode-docker
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode-remote.remote-containers
  - mstuttgart.odoo-scaffold
  - mstuttgart.odoo-snippets
  - njpwerner.autodocstring
  - redhat.ansible
  - redhat.vscode-yaml
  - sainnhe.everforest
  - standard.vscode-standard
  - teabyii.ayu
  - thenikso.github-plus-theme
  - xshrim.txt-syntax
  - yzhang.markdown-all-in-one
