# code: language=ansible
---
# tasks file for roles/gnome

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop: "{{ packages }}"

- name: Copy gnome extension to folder '{{ gnome_config_path }}'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/extensions"
    dest: "{{ gnome_config_path }}"
    follow: true
    mode: preserve

- name: Enable extensions
  community.general.system.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "{{ gnome_extensions }}"

# Configure caffeine extension

- name: Caffeine - set restore state
  community.general.system.dconf:
    key: "/org/gnome/shell/extensions/caffeine/restore-state"
    value: "true"

- name: Caffeine - disable notification
  community.general.system.dconf:
    key: "/org/gnome/shell/extensions/caffeine/show-notifications"
    value: "false"

- name: Caffeine - user
  community.general.system.dconf:
    key: "/org/gnome/shell/extensions/caffeine/user-enabled"
    value: "true"

# Configure time and date

- name: Set automatic timezone
  community.general.system.dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: Set clock to show date
  community.general.system.dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: Set clock format
  community.general.system.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

# Configure keyboard

- name: NumKLock on
  community.general.system.dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/numlock-state"
    value: "true"

# Ensure themes and icons folder

- name: 'Ensure directory exists: {{ gnome_themes_dir }}'
  ansible.builtin.file:
    path: "{{ gnome_themes_dir }}"
    state: directory
    mode: "0755"

- name: 'Ensure directory exists: {{ gnome_icons_dir }}'
  ansible.builtin.file:
    path: "{{ gnome_icons_dir }}"
    state: directory
    mode: "0755"

- name: 'Ensure directory exists: {{ fonts_dir }}'
  ansible.builtin.file:
    path: "{{ fonts_dir }}"
    state: directory
    mode: "0755"
