---
# tasks file for roles/git

- name: Install Git and Tools
  package:
    name:
      - git
      - tig
    state: present
  become: yes

- name: Link global gitignore file
  file:
    src: '{{ role_path }}/files/gitignore_global.link'
    dest: '{{ git_config_path }}/.gitignore_global'
    state: link
    force: yes

- name: Link gitattributes file
  file:
    src: '{{ role_path }}/files/gitattributes_global.link'
    dest: '{{ git_config_path }}/.gitattributes_global'
    state: link
    force: yes

- name: Override .gitconfig
  template:
    src: 'gitconfig.j2'
    dest: '{{ git_config_path }}/.gitconfig'

# Copy aliases and functions
- name: Create symbolic link to git functions in '{{ bashrc_folder }}'
  file:
    src: '{{ role_path }}/files/git.bash'
    dest: '{{ bashrc_folder }}/git.bash'
    state: link