---
# tasks file for roles/brightness/

- name: Add Brightness ppa
  become: yes
  apt_repository:
    validate_certs: no
    repo: 'ppa:apandada1/brightness-controller'
    state: present
    update_cache: yes

- name: Install Brightness
  become: yes
  apt:
    name: brightness-controller
    state: present

- name: Ensure '{{ brightness_config_dir }}' directory exists
  file:
    path: '{{ brightness_config_dir }}'
    state: directory

- name: Create Symlink to Brightness settings file in '{{ brightness_config_dir }}'
  file:
    src: '{{ role_path }}/files/settings'
    dest: '{{ brightness_config_dir }}/settings'
    state: link

- name: Ensure '{{ autostart_path }}' directory exists
  file:
    path: '{{ autostart_path }}'
    state: directory

- name: Copy Brightness .desktop file to '{{ autostart_path }}'
  file:
    src: '{{ role_path }}/files/brightness-controller.desktop'
    dest: '{{ autostart_path }}/brightness-controller.desktop'
    force: yes
