# Increase Starship command scan & duration time-outs
scan_timeout = 100
command_timeout = 3000

[c]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[python]
symbol = " "

[rust]
symbol = " "

