---

# Configure system :::::::::::::::::::::::::::::::::::::

- name: Set 'pt_BR' locale in system
  locale_gen:
    name: pt_BR.UTF-8
    state: present

- name: Set 'pt_BR' locale as default
  command: localectl set-locale LANG=pt_BR.UTF-8
  tags:
    - skip_ansible_lint

- name: Setup sysctl to fix warning to large workspace in vscode
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present
    reload: yes

- name: Add Google Sage Search in hosts file /etc/hosts
  become: yes
  blockinfile:
    dest: /etc/hosts
    marker: '# {mark} ANSIBLE MANAGED BLOCK Google Safe Search'
    block: |
      216.239.38.120

- name: Configure logind.conf, to laptop not sleep after login using external monitor
  become: yes
  lineinfile: 
    dest: '/etc/systemd/logind.conf'
    regexp: '#{{ item }}='
    line: '{{ item }}=ignore'
    state: present
  loop:
    - 'HandleLidSwitchExternalPower'
    - 'HandleLidSwitchDocked'